# Generated by Django 2.2.6 on 2019-11-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
